config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  resources :robots do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:destroy, :index, :show, :edit, :update]
  resources :pages, only: :index
end
  # resources :bookings, only: [:destroy, :index, :show]


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :robot
end

app/models/robot.rb
class Robot < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :bookings, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :robots, through: :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:destroy, :show, :edit, :update]
  before_action :set_robot, only: [:new, :create]
  def index
    @bookings = Booking.all
  end

  def show
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user

    @robot = Robot.find(params[:robot_id])
    @booking.robot = @robot
    if @booking.save
      redirect_to robot_path(@robot)
    else
      render "new", status: :unprocessable_entity
    end
  end

  def destroy
    @booking = set_booking
    @booking.destroy
    # No need  app/views/restaurants/destroy.html.erb
    # redirect_to robot_bookings_path, status: :see_other
    redirect_to robot_path
  end

  def edit

  end

  def update
    @booking.update(booking_params)
    redirect_to robot_path(@booking.robot)
  end

  private

  def booking_params
    params.require(:booking).permit(:date_first, :date_end)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_robot
    @robot = Robot.find(params[:robot_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :configure_permitted_parameters, only: :home
  def home

  end

  def index
    @user = current_user
    @robots = Robot.all
    @bookings = Booking.all
  end
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController

  before_action :set_robot, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR utility ILIKE :query OR description ILIKE :query"
      @robots = Robot.where(sql_query, query: "%#{params[:query]}%")
    else
      @robots = Robot.all
    end
    @bookings = Booking.all
  end

  def show
    @bookings = Booking.all
  end

  def new
    @robot = Robot.new
  end

  def create
    @robot = Robot.new(robot_params)
    @robot.user = current_user
    if @robot.save
      redirect_to robot_path(@robot)
    else
      render "new", status: :unprocessable_entity
    end
  end

  def destroy
    @robot.destroy
    # No need  app/views/restaurants/destroy.html.erb
    redirect_to robots_path, status: :see_other
  end

  def edit
  end

  def update
    @robot.update(robot_params)
    redirect_to robot_path(@robot)
  end

  private

  def robot_params
    params.require(:robot).permit(:name, :photo, :utility, :description)
  end

  def set_robot
    @robot = Robot.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class= "container">
<%= simple_form_for [@robot, @booking] do |f| %>
  <h2> Informations de réservations</h2>
  <br>
  <%= f.input :date_first, as: :date, input_html: {class: "toto"} %>
  <%= f.input :date_end, as: :date %>

  <br>
  <%= f.submit class: "animated-link" %>
<% end %>
</div>

app/views/bookings/_form_book.html.erb
<%= simple_form_for(booking) do |f| %>
  <h2> Informations de réservations</h2>
  <br>
  <%= f.input :date_first, as: :date %>
  <%= f.input :date_end, as: :date %>
  <br>
  <%= f.submit class: "animated-link" %>

app/views/bookings/edit.html.erb
<%= simple_form_for @booking do |f| %>
  <h2> Informations de réservations</h2>
  <br>
  <%= f.input :date_first, as: :date %>
  <%= f.input :date_end, as: :date %>

  <br>
  <%= f.submit class: "animated-link" %>
<% end %>

app/views/bookings/index.html.erb
<div class="typewriter" id="resa-title">
  <h1> Mes réservations</h1>
</div>

<div class="container-book">
  <% @bookings.each do |booking| %>
    <div class="booking-cards">
      <h5> Ta réservation avec <%= booking.robot.name %></h5>
      <%= cl_image_tag booking.robot.photo.key, height: 200, width: 300, crop: :fill, class:"show-img"%>

    <h5> Début : <%= booking.date_first%> </h5>
    <h5> Fin : <%= booking.date_end %> </h5>
  </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<%= render "form", robot: @robot %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Humanoidax</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
  <% unless action_name == "home" %>
    <%= render "devise/shared/navbar" %>
  <% end %>
    <%= yield %>
    <%= render "devise/shared/flashes" %>
  </body>
  <% unless action_name == "home" %>
    <%= render "devise/shared/footer" %>
  <% end %>
</html>

app/views/pages/home.html.erb
<div class="container-homepage">
    <div class = "login">
     <li class="animated-link">
            <%= link_to "Login", new_user_session_path%>
          </li>
     </div>


  <div class="logo">
      <%= link_to robots_path do %>
      <%= image_tag "https://res.cloudinary.com/dplkc6qh4/image/upload/v1669321616/Pasted_Graphic_mtersg.png" %>
    <% end %>
  </div>

</div>

app/views/pages/index.html.erb
<div class="container-profile">
  <div class="hello">
  <h1>Hello <%= @user.email %> ! </h1>
  <%= image_tag "https://res.cloudinary.com/dplkc6qh4/image/upload/v1669131989/EM_LA_BELLE_sqrqgt.jpg", class:"card-img-profile-picture"%>
  </div>

  <div class="h2">
    <h2>Tes Robots :</h2>
    <div class="card-container">
      <% @robots.each do |robot| %>
        <div class="robot-grid-item-profile">
            <%= link_to robot_path(robot), class: "mylink-profile" do %>
            <div class="card-product-profile">
              <%= cl_image_tag robot.photo.key, height: 250, width: 250, crop: :fill, class:"card-img-profile" %>
            </div>
                <br>
                <div class="card-product-infos-profile">
                  <h5> <%= robot.name.capitalize %> </h5>
                  <h6> <%= robot.utility.capitalize %> </h6>
                  <p> <%= robot.description.capitalize %> </p>

                </div>
          <% end %>
          </div>
    <% end %>
  </div>
  </div>
</div>




</h2>
<h2> Tes réservations :</h2>
<% @bookings.each do |booking| %>
  <h5> Début : <%= booking.date_first%> </h5>

  <h5> Fin :  <%= booking.date_end %> </h5>
  <p class ="animated-link"><%= link_to "Edit booking", edit_booking_path(booking) %></p>
  <p class ="animated-link">

  <%= link_to "Delete",
    booking_path(booking),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %>
<% end %>
  </p>

app/views/robots/_form.html.erb
<div class="container">
<%= simple_form_for(robot) do |f| %>
  <h2> Robot informations </h2>
  <br>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.input :utility %>
  <%= f.input :description %>
  <br>
  <%= f.submit class: "animated-link" %>

<% end %>

</div>

app/views/robots/edit.html.erb
<%= render "form", robot: @robot %>

app/views/robots/index.html.erb
<div class="banner">

  <div class="container1">
    <h2> Avec Humanoïdax </h2>
    <br>

    <h4> Partage ou emprunte ton robot </h4>
    <br>
    <br>
    <div class="search-barre">
      <%= form_with url: robots_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find your robot"
        %>
        <%= submit_tag "Search", class: "animated-link" %>
      <% end %>
    </div>
  </div>

</div>

<div class="container2">
  <% @robots.each do |robot| %>
        <div class="robot-grid-item">
            <%= link_to robot_path(robot), class: "mylink" do %>
            <div class="card-product">
              <%= cl_image_tag robot.photo.key, height: 250, width: 250, crop: :fill, class:"card-img" %>
            </div>
                <br>
                <div class="card-product-infos">
                  <h5> <%= robot.name.capitalize %> </h5>
                  <h6> <%= robot.utility.capitalize %> </h6>
                  <p> <%= robot.description.capitalize %> </p>

                </div>
          <% end %>
          </div>
    <% end %>
</div>

</div>

app/views/robots/show.html.erb
<div class="wrapper">
  <div class="one">
    <h1 class="typewriter"><%= @robot.name.capitalize%>, <%= @robot.utility.capitalize %></h1>

  </div>
  <div class="two">
    <%= cl_image_tag @robot.photo.key, height: 300, width: 400, crop: :fill, class:"show-img"%>
  </div>

  <div class="four">
    <p class ="animated-link"><%= link_to "Book this robot", new_robot_booking_path(@robot) %></p>
    <p class ="animated-link"><%= link_to "Edit Robot", edit_robot_path(@robot) %></p>
    <p class ="animated-link"><%= link_to "Back to Robots", robots_path %></p>
    <p class ="animated-link"><%= link_to "Delete",
    robot_path(@robot),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
    %></p>
  </div>
  <div class="five">
    <p> <%= @robot.description.capitalize %> <p>
  </div>

  <div class="six">
    <h2>Réservation </h2>
    <% @robot.bookings.each do |booking| %>
      <h5> Début <%= booking.date_first %> </h5>
      <h5> Fin <%= booking.date_end %> </h5>
  </div>
  <div class="seven">
    <p class ="animated-link" style ="width: 200px;"><%= link_to "Edit booking", edit_booking_path(booking) %></p>
    <p class ="animated-link" style ="width: 200px;">

    <%= link_to "Delete",
      booking_path(booking),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
      %>
    <% end %>
    </p>
  </div>
</div>